# Generated by Django 5.1.7 on 2025-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
